export const mockUser = {
  login: "rssviana",
  id: 16032711,
  node_id: "MDQ6VXNlcjE2MDMyNzEx",
  avatar_url: "https://avatars3.githubusercontent.com/u/16032711?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/rssviana",
  html_url: "https://github.com/rssviana",
  followers_url: "https://api.github.com/users/rssviana/followers",
  following_url: "https://api.github.com/users/rssviana/following{/other_user}",
  gists_url: "https://api.github.com/users/rssviana/gists{/gist_id}",
  starred_url: "https://api.github.com/users/rssviana/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/rssviana/subscriptions",
  organizations_url: "https://api.github.com/users/rssviana/orgs",
  repos_url: "https://api.github.com/users/rssviana/repos",
  events_url: "https://api.github.com/users/rssviana/events{/privacy}",
  received_events_url: "https://api.github.com/users/rssviana/received_events",
  type: "User",
  site_admin: false,
  name: "Ronan Viana",
  company: "@stone-payments ",
  blog: "https://rssviana.github.io/mypage/",
  location: "Rio de Janeiro",
  email: null,
  hireable: null,
  bio: "Em ciências da computação; programador, desenvolvedor, codificador ou engenheiro de software é alguém que escreve, desenvolve ou faz manutenção de software.",
  twitter_username: null,
  public_repos: 17,
  public_gists: 0,
  followers: 2,
  following: 2,
  created_at: "2015-11-26T12:16:37Z",
  updated_at: "2020-10-13T03:12:41Z"
}
